# Generated by Django 4.2.4 on 2023-08-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("point_of_sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("serial", models.CharField(max_length=3, unique=True)),
                ("init", models.IntegerField()),
                ("end", models.IntegerField()),
                ("expiration", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="input",
            name="invoice_number",
            field=models.CharField(max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="input",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.provider",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceheader",
            name="number",
            field=models.CharField(max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SequenceReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="point_of_sales.receipt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoiceheader",
            name="receipt_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="point_of_sales.receipt"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceheader",
            name="sequence_receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.sequencereceipt",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="sequencereceipt",
            constraint=models.UniqueConstraint(
                fields=("receipt", "sequence"), name="unique_sequence_receipt"
            ),
        ),
    ]
