# Generated by Django 4.2.4 on 2023-08-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("point_of_sales", "0002_receipt_input_invoice_number_input_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="invoice_header",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_detial",
                to="point_of_sales.invoiceheader",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="sequence_receipt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.sequencereceipt",
                unique=True,
            ),
        ),
    ]
