# Generated by Django 4.2.4 on 2023-08-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0004_documenttype_status_invoiceheader_status_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='invoice_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_detail', to='point_of_sales.invoiceheader'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
