# Generated by Django 4.2.4 on 2023-08-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0005_invoiceheader_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceheader',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoiceheader',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoiceheader',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoiceheader',
            name='total_tax',
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type', to='point_of_sales.documenttype'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='point_of_sales.item'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='point_of_sales.customer'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_of_sales.paymentmethod')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='Payment',
            field=models.ManyToManyField(default=0.0, to='point_of_sales.payment'),
        ),
    ]
