# Generated by Django 4.2.4 on 2023-08-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("point_of_sales", "0006_remove_invoiceheader_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceheader",
            name="Payment",
        ),
        migrations.RemoveField(
            model_name="invoiceheader",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="point_of_sales.invoiceheader",
            ),
            preserve_default=False,
        ),
    ]
