# Generated by Django 4.2.4 on 2023-09-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0007_remove_invoiceheader_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencereceipt',
            name='sequence',
            field=models.CharField(max_length=12),
        ),
    ]
