# Generated by Django 4.2.4 on 2023-09-14 13:31

from django.db import migrations, models
import django.db.models.deletion

# import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("point_of_sales", "0011_alter_company_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceheader",
            name="receipt_type",
        ),
        migrations.RemoveField(
            model_name="invoiceheader",
            name="sequence_receipt",
        ),
        migrations.AddField(
            model_name="sequencereceipt",
            name="expiration",
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sequencereceipt",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_sequence",
                to="point_of_sales.invoiceheader",
            ),
        ),
    ]
