# Generated by Django 4.2.4 on 2023-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0013_quotationheader_quotationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationheader',
            name='customer',
            field=models.JSONField(null=True),
        ),
    ]
