# Generated by Django 4.2.4 on 2024-01-30 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("point_of_sales", "0014_alter_quotationheader_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Compañia", "verbose_name_plural": "Compañias"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "verbose_name": "Tipo de documento",
                "verbose_name_plural": "Tipos de documento",
            },
        ),
        migrations.AlterModelOptions(
            name="input",
            options={"verbose_name": "Entrada", "verbose_name_plural": "Entradas"},
        ),
        migrations.AlterModelOptions(
            name="invoiceheader",
            options={"verbose_name": "Factura", "verbose_name_plural": "Facturas"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Artículo", "verbose_name_plural": "Artículos"},
        ),
        migrations.AlterModelOptions(
            name="output",
            options={"verbose_name": "Salida", "verbose_name_plural": "Salidas"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Pago", "verbose_name_plural": "Pagos"},
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "Metodo de pago",
                "verbose_name_plural": "Metodos de pago",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
        migrations.AlterModelOptions(
            name="quotationheader",
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
            },
        ),
        migrations.AlterModelOptions(
            name="return",
            options={
                "verbose_name": "Devolución",
                "verbose_name_plural": "Devoluciones",
            },
        ),
        migrations.AlterModelOptions(
            name="saletype",
            options={
                "verbose_name": "Tipo de venta",
                "verbose_name_plural": "Tipos de venta",
            },
        ),
        migrations.AlterModelOptions(
            name="sequencereceipt",
            options={
                "verbose_name": "Secuencia de comprobante",
                "verbose_name_plural": "Secuencia de comprobantes",
            },
        ),
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name": "Impuesto", "verbose_name_plural": "Impuestos"},
        ),
        migrations.RemoveField(
            model_name="invoicedetail",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="item",
            name="tax",
        ),
        migrations.AddField(
            model_name="invoiceheader",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=3, verbose_name="Impuesto"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="stock_max",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Maximo"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="stock_min",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Minimo"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.tax",
                verbose_name="Impuesto",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="document_id",
            field=models.CharField(
                max_length=15, null=True, verbose_name="No. Documento"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_document_type",
                to="point_of_sales.documenttype",
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document_id",
            field=models.CharField(
                max_length=15, null=True, verbose_name="No. Documento"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_type",
                to="point_of_sales.documenttype",
                verbose_name="Tido de documento",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre completo"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="input",
            name="date_of_entry",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de entrada"
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="invoice_number",
            field=models.CharField(max_length=12, verbose_name="No. Factura"),
        ),
        migrations.AlterField(
            model_name="input",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.item",
                verbose_name="Artículo",
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.provider",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="purchase_order",
            field=models.CharField(max_length=12, verbose_name="Orden de compra"),
        ),
        migrations.AlterField(
            model_name="input",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="comment",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Comentarios"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="point_of_sales.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Descuento"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="number",
            field=models.CharField(
                editable=False, max_length=12, unique=True, verbose_name="No. Factura"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="sales_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.saletype",
                verbose_name="Tipo de venta",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="status",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceheader",
            name="user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_service",
            field=models.BooleanField(default=False, verbose_name="Servicio?"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Precio"
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="provider",
        ),
        migrations.AlterField(
            model_name="item",
            name="reference",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Referencia"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="output",
            name="departure_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de salida"
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.item",
                verbose_name="Artículo",
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="output",
            name="reason",
            field=models.CharField(max_length=50, verbose_name="Razón"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Monto"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="point_of_sales.invoiceheader",
                verbose_name="Factura",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.paymentmethod",
                verbose_name="Método de pago",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="address",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="document_id",
            field=models.CharField(max_length=15, verbose_name="No. Documento"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.documenttype",
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estatus"),
        ),
        migrations.AlterField(
            model_name="quotationdetail",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="comment",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Comentarios"
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="customer",
            field=models.JSONField(null=True, verbose_name="Cliente"),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Descuento"
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="number",
            field=models.CharField(
                editable=False,
                max_length=12,
                unique=True,
                verbose_name="No. Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="sales_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.saletype",
                verbose_name="Tipo de venta",
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="status",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quotation_user_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="quotationheader",
            name="user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quotation_user_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="end",
            field=models.IntegerField(verbose_name="Fin secuencia"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="expiration",
            field=models.DateField(verbose_name="Fecha de expiración"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="init",
            field=models.IntegerField(verbose_name="Inicio secuencia"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="name",
            field=models.CharField(max_length=25, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="return",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sales.item",
                verbose_name="Artículo",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="return",
            name="reason",
            field=models.CharField(max_length=50, verbose_name="Razón"),
        ),
        migrations.AlterField(
            model_name="return",
            name="return_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de devolución"
            ),
        ),
        migrations.AlterField(
            model_name="saletype",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="saletype",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="expiration",
            field=models.DateField(verbose_name="fecha de expiración"),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_sequence",
                to="point_of_sales.invoiceheader",
                verbose_name="Factura",
            ),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequence",
                to="point_of_sales.receipt",
                verbose_name="Comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="sequence",
            field=models.CharField(max_length=12, verbose_name="Secuencia"),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="sequencereceipt",
            name="to_reuse",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Reusar"
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="tax",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Porcentaje"
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="item",
            name="provider",
            field=models.ManyToManyField(
                to="point_of_sales.provider", verbose_name="Proveedor"
            ),
        ),
    ]
