# Generated by Django 4.2.4 on 2024-02-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sales", "0016_invoiceheader_avance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotationdetail",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="quotationheader",
            name="customer",
        ),
        migrations.AddField(
            model_name="quotationheader",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=3, verbose_name="Impuesto"
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quotationheader",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_customer",
                to="point_of_sales.customer",
                verbose_name="Cliente",
            ),
            preserve_default=False,
        ),
    ]
