# Generated by Django 4.2.4 on 2024-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0017_remove_quotationdetail_tax_quotationheader_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetail',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Descripcion'),
        ),
    ]
