# Generated by Django 4.2.4 on 2024-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0018_quotationdetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='quotationdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje'),
        ),
    ]
