# Generated by Django 4.2.4 on 2024-03-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('point_of_sales', '0020_item_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='tax',
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type', to='master_data.documenttype', verbose_name='Tido de documento'),
        ),
        migrations.AlterField(
            model_name='input',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='No. Factura'),
        ),
        migrations.AlterField(
            model_name='input',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='sales_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.saletype', verbose_name='Tipo de venta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.paymentmethod', verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='quotationheader',
            name='sales_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.saletype', verbose_name='Tipo de venta'),
        ),
        migrations.AlterField(
            model_name='sequencereceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='master_data.receipt', verbose_name='Comprobante'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='SaleType',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
