# Generated by Django 4.2.4 on 2024-03-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "point_of_sales",
            "0021_remove_receipt_tax_alter_customer_document_type_and_more",
        ),
    ]

    operations = [
        #migrations.RemoveConstraint(
        #    model_name="customer", name="unique_customer_document_type_and_id"
        #),
        #migrations.RemoveConstraint(
        #    model_name="provider", name="unique_provide_document_type_and_id"
        #),
        #     migrations.RemoveField(
        #         model_name='customer',
        #         name='document_type',
        #     ),
        #     migrations.RemoveField(
        #         model_name='input',
        #         name='item',
        #     ),
        #     migrations.RemoveField(
        #         model_name='input',
        #         name='provider',
        #     ),
        #     migrations.RemoveField(
        #         model_name='item',
        #         name='provider',
        #     ),
        #     migrations.RemoveField(
        #         model_name='output',
        #         name='item',
        #     ),
        #     migrations.RemoveField(
        #         model_name='payment',
        #         name='invoice',
        #     ),
        #     migrations.RemoveField(
        #         model_name='payment',
        #         name='payment_method',
        #     ),
        #     migrations.RemoveField(
        #         model_name='provider',
        #         name='document_type',
        #     ),
        #     migrations.RemoveField(
        #         model_name='return',
        #         name='item',
        #     ),
    ]
