# Generated by Django 4.2.4 on 2024-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0023_alter_invoicedetail_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceheader',
            name='avance',
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='inactive_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='pending_payment',
            field=models.BooleanField(default=True, editable=False, verbose_name='pendiente de pago'),
        ),
    ]
