# Generated by Django 4.2.4 on 2024-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_and_providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_provide_document_type_and_id',
        ),
        migrations.AlterField(
            model_name='provider',
            name='document_id',
            field=models.CharField(max_length=15, null=True, verbose_name='No. Documento'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('document_id__isnull', False)), fields=('document_type', 'document_id'), name='unique_provide_document_type_and_id'),
        ),
    ]
