# Generated by Django 4.2.4 on 2024-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('reference', models.CharField(blank=True, max_length=60, null=True, verbose_name='Referencia')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('stock', models.IntegerField(default=0)),
                ('stock_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimo')),
                ('stock_max', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maximo')),
                ('is_service', models.BooleanField(default=False, verbose_name='Servicio?')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
