# Generated by Django 4.2.4 on 2024-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases_and_providers', '0001_initial'),
        ('products_and_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.ManyToManyField(to='purchases_and_providers.provider', verbose_name='Proveedor'),
        ),
    ]
