# Generated by Django 4.2.4 on 2024-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('purchase_order', models.CharField(blank=True, max_length=12, null=True, verbose_name='Orden de compra')),
                ('invoice_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='No. Factura')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrada')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('reason', models.CharField(max_length=50, verbose_name='Razón')),
                ('departure_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de salida')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('reason', models.CharField(max_length=50, verbose_name='Razón')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de devolución')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
    ]
