# Generated by Django 4.2.4 on 2024-03-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products_and_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_and_services.item', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='output',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_and_services.item', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='input',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_and_services.item', verbose_name='Artículo'),
        ),
    ]
