# Generated by Django 4.2.4 on 2024-03-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0002_remove_customer_unique_customer_document_type_and_id_and_more",
        ),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name="customer",
        #     options={},
        # ),
        # migrations.RemoveConstraint(
        #    model_name="customer",
        #    name="unique_customer_document_type_and_id",
        #),
    ]
