# Generated by Django 4.2.4 on 2024-03-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de venta',
                'verbose_name_plural': 'Tipos de venta',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('serial', models.CharField(max_length=3, unique=True)),
                ('init', models.IntegerField(verbose_name='Inicio secuencia')),
                ('end', models.IntegerField(verbose_name='Fin secuencia')),
                ('expiration', models.DateField(verbose_name='Fecha de expiración')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('tax', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.tax', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('document_id', models.CharField(max_length=15, null=True, verbose_name='No. Documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dirección')),
                ('logo', models.ImageField(upload_to='company/')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_document_type', to='master_data.documenttype', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
            },
        ),
    ]
