# Generated by Django 4.2.4 on 2024-05-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Condición', 'verbose_name_plural': 'Condiciones'},
        ),
    ]
