# Generated by Django 4.2.4 on 2024-03-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0002_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="inactive_comment",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="user_created",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_user_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="user_updated",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_user_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
            preserve_default=False,
        ),
    ]
