# Generated by Django 4.2.4 on 2024-05-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0024_remove_invoiceheader_avance_and_more'),
        ('accounting', '0003_payment_inactive_comment_payment_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='point_of_sales.invoiceheader', verbose_name='Pago'),
        ),
    ]
